services:
  db:
    image: postgres:14
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  train_model:
    build:
      context: .
      dockerfile: Dockerfile_modeling
    container_name: train_model
    env_file:
      - .env
    command: ["python", "-m", "main", "train-model"]

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile_api
    container_name: fastapi
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: ["poetry", "run", "uvicorn", "api.app:app", "--host", "0.0.0.0", "--port", "8000"]
